import { jsPDF } from 'jspdf'
import { DocumentType } from '@prisma/client'

export async function generateAviationPDF(type: DocumentType, data: any) {
  const doc = new jsPDF()
  
  // Header
  doc.setFontSize(18)
  doc.text('PART-CAO MAINTENANCE ORGANIZATION', 105, 20, { align: 'center' })
  doc.setFontSize(14)
  doc.text(`${type} - ${getTypeLabel(type)}`, 105, 30, { align: 'center' })
  
  // Balloon Info Box
  doc.setFontSize(10)
  doc.rect(20, 40, 170, 30)
  doc.text(`Registration: ${data.registration}`, 25, 50)
  doc.text(`Manufacturer: ${data.manufacturer}`, 25, 60)
  doc.text(`Model: ${data.model}`, 110, 50)
  doc.text(`Serial Number: ${data.serialNumber}`, 110, 60)
  
  // Content Area
  doc.setFontSize(12)
  doc.text('Maintenance Statement:', 20, 85)
  doc.setFontSize(10)
  doc.text('I hereby certify that the work specified has been carried out in accordance with', 20, 95)
  doc.text('the maintenance program and complies with Part-ML/Part-CAO requirements.', 20, 100)
  
  // Signature Field
  doc.rect(120, 150, 60, 30) // Boundary for signature
  doc.text('SIGNATURE / STAMP', 150, 185, { align: 'center' })
  
  // Footer
  doc.setFontSize(8)
  doc.text('Document Generated by CAO APP MVP. Official Record.', 105, 285, { align: 'center' })
  
  return doc.output('arraybuffer')
}

function getTypeLabel(type: DocumentType) {
  switch (type) {
    case 'TR': return 'Task Report'
    case 'DR': return 'Defects Report'
    case 'DDL': return 'Deferred Defects List'
    case 'ML': return 'Modifications List'
    case 'CRS': return 'Certificate of Release to Service'
    default: return type
  }
}
